In [3]:
import numpy as np

arr = np.array([[0], [2]])

In [4]:
arr

array([[0],
       [2]])

In [5]:
arr2 = np.ones((10, 10))

In [6]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr2.shape

(10, 10)

In [15]:
arr3 = np.zeros((10,10), dtype="float16")
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float16)

In [17]:
np.c_[arr2, arr3][0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [19]:
[arr2, arr3][0]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
arr4 = np.full((5, 5), fill_value=[1, 2, 3, 4, 5], dtype="float32")

In [25]:
arr4

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]], dtype=float32)

In [27]:
np.c_[arr4, arr4]

array([[1., 2., 3., 4., 5., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 1., 2., 3., 4., 5.]], dtype=float32)

In [28]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.c_[np.array([[1, 11], [2,22], [3,33], [4, 44], [5, 55]]), np.array([[6, 66], [7,77], [8,88], [9,99], [10,1010]])]

array([[   1,   11,    6,   66],
       [   2,   22,    7,   77],
       [   3,   33,    8,   88],
       [   4,   44,    9,   99],
       [   5,   55,   10, 1010]])

In [35]:
np.r_[np.array([[1, 11], [2,22], [3,33], [4, 44], [5, 55]]), np.array([[6, 66], [7,77], [8,88], [9,99], [10,1010]])]

array([[   1,   11],
       [   2,   22],
       [   3,   33],
       [   4,   44],
       [   5,   55],
       [   6,   66],
       [   7,   77],
       [   8,   88],
       [   9,   99],
       [  10, 1010]])

In [36]:
X = 2 * np.random.rand(100, 1)

In [37]:
X

array([[1.89599282],
       [0.40579177],
       [1.23745843],
       [1.57214843],
       [0.52890222],
       [0.00788481],
       [0.61055498],
       [1.16164886],
       [1.50157336],
       [0.11883498],
       [0.03948808],
       [1.79222804],
       [1.39627946],
       [1.3361849 ],
       [1.03181901],
       [0.32010957],
       [0.73558868],
       [0.08884502],
       [1.65126124],
       [1.12147237],
       [0.58257592],
       [0.30250215],
       [1.89988975],
       [1.12809624],
       [0.62997348],
       [0.93289419],
       [1.16079957],
       [1.01465565],
       [1.2909621 ],
       [0.33876621],
       [0.59757159],
       [1.92359014],
       [0.20809919],
       [1.84912386],
       [0.17605053],
       [0.11792392],
       [1.31424245],
       [0.14257948],
       [0.14246638],
       [0.78131874],
       [0.45957934],
       [0.76975719],
       [1.13073207],
       [1.35295494],
       [1.16271488],
       [0.38137391],
       [1.74048742],
       [0.471

In [42]:
arr5=np.array([[[0,0]],[[1,1]]]).shape
arr5

(2, 1, 2)

In [45]:
tst1 = np.c_[np.ones((3,1)), np.zeros((3,1))]
tst1

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [47]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [48]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [51]:
np.ones((3,1,2))

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]])

In [53]:
tst2 = np.c_[np.ones((3,1,2)), np.zeros((3,1,2))]
tst2

array([[[1., 1., 0., 0.]],

       [[1., 1., 0., 0.]],

       [[1., 1., 0., 0.]]])